# Generated by Django 3.2.4 on 2021-08-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210804_0545'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
            ],
            options={
                'db_table': 'users_colors',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='usercolor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.ManyToManyField(related_name='users', through='users.UserColor', to='products.Color'),
        ),
    ]
